### ISSUE TITLE
Data Source for Linked tables that reside in the same folder as the Source not saving absolute path

### ISSUE THREAD

**Issue by alanv73** [joyfullservice/msaccess-vcs-addin#342]
I ran into this issue when exporting back end databases that contain linked tables from another back end database.

The source of the linked table resides in the same folder as the database containing the link. The Linked Table Manager contains the full absolute path:

![vcs_error1](https://user-images.githubusercontent.com/29257817/179007308-df59f768-7c8e-4583-ac9a-586038f6934f.png)

After export, the table information in the source folder contains a relative path:

```
{
  "Info": {
    "Class": "clsDbTableDef",
    "Description": "Linked Table"
  },
  "Items": {
    "Name": "tblTracking",
    "Connect": ";DATABASE=rel:Tracking.accdb",
    "SourceTableName": "tblTracking",
    "Attributes": 1073741824,
    "PrimaryKey": "[LogID]"
  }
}
```

If I copy my source folder to a test folder and attempt to build the database, an error occurs because it can't find the source databases. If the full absolute path was preserved it wouldn't matter what folder contained the database.

![vcs_error](https://user-images.githubusercontent.com/29257817/179008189-6c330fd8-a4ee-4492-a374-67357eff1618.png)

The same table linked from a front end database that resides in a different folder than the source (usually on the user's computer) exports correctly:

```
{
  "Info": {
    "Class": "clsDbTableDef",
    "Description": "Linked Table"
  },
  "Items": {
    "Name": "tblTracking",
    "Connect": ";DATABASE=\\\\arpmserv1\\common\\Databases\\Tracking.accdb",
    "SourceTableName": "tblTracking",
    "Attributes": 1073741824,
    "PrimaryKey": "[LogID]"
  }
}
```

**Comment by joyfullservice** [comment]
Hi @alanv73, what you are describing above is the expected behavior in how the add-in is presently designed to work. If a linked data source is in the same folder, a relative path is used. This gives projects a greater level of portability and reduces the absolute paths stored in version control.

One approach would be to place your back-end databases in a different folder. That's what we do where I work. We have about 30 different back-end databases in a `_Data` folder. They have the same name as the application, but with a " Data" suffix. (I.e. "Job Tracker Data.accdb" corresponds to the "Job Tracker" deployed application.) With this approach I can build the front-end applications anywhere because the linked tables use absolute paths.

Another project involves two back-end files, one that is local and paired with the deployed application, and the other that is on the server. (This is for a POS system with offline capabilities.) I keep both the front-end application and the local back-end file in the same GitHub repo. If I am building it on a new computer, I build the back end file first, then build the front end. This allows full portability of the project even though I use both relative and absolute linked tables.

Hope that helps!

**Comment by alanv73** [comment]
> We have about 30 different back-end databases in a _Data folder.

It sounds like you have 30 back-end databases in the same folder.

What if, for convenience, you place a couple of table links in one of them that points to another. 

It becomes really difficult to build the database with the linked tables because the target database must be in the same folder at build time.

The only way this works is if you only keep a single back-end database in each folder.

**Comment by joyfullservice** [comment]
> It sounds like you have 30 back-end databases in the same folder.
> 
> What if, for convenience, you place a couple of table links in one of them that points to another.
> 

Thanks for the clarification on this. I can see how that would be a challenge.

In our environment, I keep the back end databases very simple. They don't have any code, any recursive links to other back end databases. They just have tables. (And yes, the majority of them are all in the same folder.) I do all the relationships and linking of different tables from different back end sources all in the front-end application databases, which are managed in version control on my workstation. (We deploy the front-end databases to the computers of the end users, rather than running them from the server.)

Personally, I like keeping the build environment autonomous from the production environment. In other words, rather than building directly on the server, I build on my computer, then deploy working/completed builds out to the server (or end users). Private GitHub or GitLab repros are great for this, and exactly what this add-in is designed for. When used along with GitHub Desktop for Windows, I find this to be a very simple and efficient way to manage the database applications. 

I simply clone the repro to my machine, build from source, and I am right into the development phase. When I am done, I deploy the app (by typing a single command), commit my changes back to the repro, and we are off and running with the latest updates. If my colleague wants to make some changes on a project, he simply pulls down the changes in GitHub Desktop, builds from source, and he is right where I left off.

While the above workflow seems to work really well for us, I totally understand that each developer/team has to work out the approach that is going to work best for their needs in their environment. My goal with the add-in is to have something that will bring the greatest level of efficiency to the widest selection of use cases, so that is why I took the approach I did with the relative paths. That said, I am certainly open to suggestions and ideas on how we can reasonably improve it.  😄

**Comment by joyfullservice** [comment]
To summarize this issue, this add-in is designed to utilize relative paths wherever possible to keep builds as portable as possible. This may create an issue in some specific folder structures where it may be desirable to link tables using an absolute path rather than a relative one. If a relative path is not desired for the linked table, you could consider the following two workarounds:

### Workaround 1
One approach is to utilize a folder structure that places the linked database in a different folder from the application. When the linked database does not exist in the same folder, then full path will be stored in version control.

### Workaround 2
Another approach, which is probably better suited for this particular situation, is to utilize the `BeforeBuild` and/or `AfterBuild` hooks to call a sub in your database to relink the tables as desired.
