### ISSUE TITLE
Build hangs on importing linked table having invalid path.

### ISSUE THREAD

**Issue by joshbooker** [joyfullservice/msaccess-vcs-addin#409]
I found build hangs on importing tables when we have a linked table with an old, non-existent path. 

No error pops and it hangs indefinitely 'not responding' with high cpu. I was able to delete the respective tbldefs files(s) and remove the same from the index.json file and the build worked rather fast as expected.

It'd be nice if the error was handled gracefully. "UNABLE TO LINK TABLE BLAH. PATH NOT FOUND" Continue?

Thanks for this tool. wish I knew about it years ago. keep up the great work!

**Comment by joshbooker** [comment]
possibly related: #307

**Comment by joyfullservice** [comment]
Thanks, Josh! I will see if I can test this on the latest `dev` build to see if it is still an issue. Like you said, it would be helpful to handle this condition gracefully.

**Comment by joyfullservice** [comment]
I was able to test this using `Testing.accdb` by renaming the linked CSV file so the build would not be able to locate it. The add-in showed the error on the build summary, and the full paths were listed in the log file. I did find a related issue where a custom object description could not be applied to this object because it was not created during the build, but I will address that in another commit shortly.

![image](https://github.com/joyfullservice/msaccess-vcs-addin/assets/7254992/52634035-36d2-42ac-ba57-a3832db5efa0)

There may be some types of errors, such as ODBC connection timeouts that we may not be able to easily trap before they go into a timeout phase. I am open to suggestions on better ways to handle those, but I would guess that these should be pretty infrequent on actively developed projects.

**Comment by joshbooker** [comment]
Thanks Adam.  I've tried to recreate the problem with an Access linked table using testing.accde (after removing the code that relinks tables to current path on open) but it handles a bad path gracefully with error and continues.

Also, I tested build of my export after creating the file/tbl at the bad path (making it good) and the build ran fine.  Then I renamed the file and re-build hangs again. 

![image](https://github.com/joyfullservice/msaccess-vcs-addin/assets/2698896/5859423a-f2e6-4c8b-82d6-f3abc67aa6c6)

Further, after crashing out of Access and opening the partial built file I can see it hung on the table in question due to import sequence.

So either fixing the bad path or deleting the table from the project json builds successfully.   

Why?

Tried to debug in the add-in and ImportLinkedTable function is definitely throwing 3044 error at `dbs.TableDefs.Append tdf` as expected but I cannot debug any further.

![image](https://github.com/joyfullservice/msaccess-vcs-addin/assets/2698896/23a871df-f5b9-4f1a-bfaf-bf1b050634dc)

Mystery I guess.  Thanks again.

**Comment by joyfullservice** [comment]
Thanks! It looks like there are at least a couple more error numbers Access uses when it has problems linking to a Microsoft Access database table. I added these to the error handler, so that should fix the issue, at least for these two situations.

I need to review things a little further because the following `CatchAny` call should have trapped the error without an application hang...

**Comment by joshbooker** [comment]
Not one to give up i tried to debug the addin further.  I got Error: 28 out of stack space after `CatchAny` in function `ImportLinkedTable`.  When I stepped into `CatchAny` it indeed caught the error 3044 as expected but coming out got Err28

```        dbs.TableDefs.Append tdf
        If Catch(3011) Then
            Log.Error eelError, "Could not link table '" & dItem("SourceTableName") & "'", _
            ModuleName & ".ImportLinkedTable"
            Log.Add "Linked table object not found in " & strFile, False
            Log.Add "Connection String: " & strConnect, False
        ElseIf CatchAny(eelError, vbNullString, ModuleName & ".ImportLinkedTable", True, False) Then
            ' May have encountered other issue like a missing link specification.
            MsgBox Err & ": " & Err.Description & vbCrLf & "File: " & strFile
            Err.Clear
        Else
```
I prevented `Err.Clear` on `CatchAny` call and added the `MsgBox` and `Err.Clear` and upon clicking ok to the msg the Build continued and completed successfully.

![image](https://github.com/joyfullservice/msaccess-vcs-addin/assets/2698896/ea1d87aa-82a5-4897-b0f3-8e7d9d1b9343)

The only side effect noticed is the progress textbox and build log had many blank lines (124-996) and the 3044 error did not post to either place.

Hope this helps(?)

**Comment by joyfullservice** [comment]
Thanks! Yes, that is helpful, and explains why Access was hanging. It probably does have to do with the function that checks for unhandled errors going into a loop... I know I refactored that recently, and might have introduced a bug. I will look at this when I have a chance.

**Comment by hecon5** [comment]
@joyfullservice  Is this solved?

**Comment by joyfullservice** [comment]
Yes, I believe this has been resolved. We can reopen the issue if we have any further problems with this.
