### ISSUE TITLE
Feature: Add option to allow disabling of SQL Formatting 

### ISSUE THREAD

**Issue by hecon5** [joyfullservice/msaccess-vcs-addin#443]
I think it'd be good to add an option for whether we want the SQL formatter to run on both internal tables / queries and the external ones. 

We've adopted a specific formatting (comma before) style for our SQL tables, and having the formatter alter that and remove whitespace isn't desired. 

We'd also like to be able to disable the formatting on internal objects as well, simply because it's unexpected.

**Comment by joyfullservice** [comment]
The current version of the dev branch includes the option to turn off the SQL formatter if you prefer to take a different approach for your projects.

![image](https://github.com/joyfullservice/msaccess-vcs-addin/assets/7254992/089e2d6b-6720-4c71-a419-514a5b65271b)

My hunch is that most users will benefit from the formatting, so that's why the option is on by default, but I certainly understand that some users will have specific ways they want to do this, and can incorporate those into the AfterExport hook.

I am happy to consider some small tweaks to the formatter for things like using a preceding comma instead of a trailing one, as long as it doesn't add a lot of complexity to the formatter class.

The only thing the formatter is currently being applied to is internal Access queries. I suppose we could use it with table definitions for consistency, but that's not currently implemented. I will probably also use it in the future on MySQL view definitions since you can't preserve layouts on those objects.

I am not sure I quite follow what you are saying about internal objects... Maybe I am misunderstanding something?

**Comment by hecon5** [comment]
I thought I replied to this a while ago...oh well! 

I totally missed this option when I built last, whoops.

As to customization, I think comma before/after is about the only devaition we have from "normally" linted SQL code.

Internal objects: I think my coffee addled brain meant "hidden system tables"...but I can't remember what I meant at this point, clearly the thought could've used some more brewing...better get more coffee.
