### ISSUE TITLE
Table attribute weirdness

### ISSUE THREAD

**Issue by ollypsilon** [joyfullservice/msaccess-vcs-addin#462]
When testing 4.0.28 I stumbled over this.
Not sure it's just related to VCS add-in or a mix of system table garbage.

One of the (hidden) tables `Debit Note` is not shown when ticking `Show Hidden`:
![image](https://github.com/joyfullservice/msaccess-vcs-addin/assets/52780811/53e8f258-42b0-4529-b7ab-5fbd29a1e5e2)

It appears when I also select `Show System`:
![image](https://github.com/joyfullservice/msaccess-vcs-addin/assets/52780811/2b9e8d24-97f2-4b4f-b9bc-11daa879bb31)

But it's not a system object for Access, at least it's not hidden in navigation pane as you can see.
Strange as is, when I unselect `Show Hidden` to just show system tables it disappears again:
![image](https://github.com/joyfullservice/msaccess-vcs-addin/assets/52780811/46d8f9c7-9676-4c59-b157-73fd89ef06ba)

What's unclear for me is the different flags in system object:
![image](https://github.com/joyfullservice/msaccess-vcs-addin/assets/52780811/ded69c75-da51-4fa9-a8f0-2fa3b3a63671)

Still, navigation pane doesn't get mixed with hiding/unhiding hidden and/or system objects, but VCS add-in does.

**Comment by hecon5** [comment]
Is this a new occurrence or you just noticed it?

**Comment by ollypsilon** [comment]
It's new to me, didn't had this in previous exports (as system objects are not exported).
Tomorrow I might be able to check it in a backup of and old dev system where no database changes happen and add-in wasn't updated. Maybe narrows the scope...

**Comment by joyfullservice** [comment]
I think the issue here is how we determine that a table is a _system tables_. Here is how the code currently does it:

![image](https://github.com/joyfullservice/msaccess-vcs-addin/assets/7254992/a7299473-3f48-4c0e-9c23-f8fc16bc7ffe)

For your `Debit Note` table, it is correctly identified as a hidden table (using bit 8 in the flags). But it is also identified as a system table because the flags are set to more than just hidden.

Colin Riddington has a [great resource](https://isladogs.co.uk/purpose-of-system-tables-2/index.html#TFE) that I used to identify the table type based on the flags. Based on this, I think I will go ahead and switch to the simpler approach of just checking for the bit flag 2 to identify a system table.

```vba
' Before
rstTableData!IsSystem = ((lngFlags <> 0) And (lngFlags <> 8) And (lngType = 1))
' After
rstTableData!IsSystem = BitSet(lngFlags, 2)
```
This should solve the issue for your database, although it remains a bit of a mystery how that table picked up that particular flag value and exactly what it means.

**Comment by hecon5** [comment]
Is this fixed?
