### ISSUE TITLE
Bug: Build fails on e29d48b

### ISSUE THREAD

**Issue by hecon5** [joyfullservice/msaccess-vcs-addin#483]
When trying to build the latest VCS (e29d48bd14a53347ab35222caf5875bebec7daa3), I notice it fails when attempting to run the after build commands. This appears to be due to trying to run a project with the same name when running, but I'm not certain. 

![image](https://github.com/joyfullservice/msaccess-vcs-addin/assets/54177882/d8d4eb5a-2755-49b4-a20b-ccf01fe3d921)

Edit: Should be noted, if you click "End" on the debug notice this will crash out Access entirely on my machine.

**Comment by joyfullservice** [comment]
@hecon5 - That's a bit of a catch-22. 😄 The add-in was recently updated to support the `AfterBuild` function for the add-in itself, but you have to have a newer build for this functionality to actually run. In other words, you need the build you are trying to create in order to successfully build it. Obviously installing the next dev build will solve the issue for future builds.

But the good news is that it is pretty simple to work around this. You can just remove the `RunAfterBuild` value in the VCS options file, then you should be able to build successfully. After installing the new build, you can then restore the option and build again if you wish. (At the moment the AfterBuild function simply verifies some internal resources.)

I might roll out an updated dev build if I have a chance later today. (Or sometime soon.)

Regarding the app crash when ending the running code, that is pretty much expected due to the complexities of object references during a build operation. My advice there is don't end the VBA code when running the add-in. You can use the debugger to step around the offending code to continue. If you crash the VBA editor, there is a pretty good change you might corrupt the add-in file. To recover from this, simply reinstall a known good copy of the add-in, and build from source to get back to the previous state.

**Comment by hecon5** [comment]
heh, I was able to rebuild it by following your steps, so I'll close it, perhaps "has workaround" can be a tag, but that works for me!
