### ISSUE TITLE
Formated SQL issue with columnname "groups"

### ISSUE THREAD

**Issue by Tanarri** [joyfullservice/msaccess-vcs-addin#487]
Hi,

I found a reproduceable issue at exporting SQL-Query, when in the settings "format SQL" is checked.

The SQL Query, which is produce a faulty formatted SQL is:
(yes, I know that the SQL command makes no sense)
```
SELECT MSysObjects.DateCreate, MSysObjects.Flags AS groups
FROM MSysObjects;
```

and the query it exported formatted:
```
SELECT
  MSysObjects.DateCreate,
  MSysObjects.Flags AS
groups
FROM
  MSysObjects;
```

Please note the additional line break before "groups".
The correct formatted SQL should be:
```
SELECT
  MSysObjects.DateCreate,
  MSysObjects.Flags AS groups
FROM
  MSysObjects;
```

It's just an inconvenience, but everything works.

Greetings

**Comment by joyfullservice** [comment]
The issue here is that `GROUPS` is actually a reserved word in MySQL, (even though it is not reserved in Microsoft Access) so this was treated as a reserved top level word in the formatting.

I am trying to keep this formatter class simple, rather than expanding into class interfaces for each supported dialect. As a compromise, I have added an additional list of keywords used by Microsoft Access SQL. If the query being formatted is Microsoft Access SQL, it will run the regular logic for different sets of keywords, but then apply an additional filter at the end to confirm that the keyword is one used by Microsoft Access. 

In my estimation, this should resolve about 95% of the scenarios most users would encounter when using names that are reserved words in other dialects. It's not perfect in that an alias used in a Microsoft SQL Server query might be fine in MSSQL, but a reserved word in MySQL. In that case it will be treated as a reserved word, even though it technically is not in the specified dialect. Without expanding into a much more complex parser, I feel like this is a reasonable compromise.

Let me know if you encounter any other issues!

**Comment by Tanarri** [comment]
I have tested your solution and it works great.

Now I don't have any issues with the SQL formating!
