### ISSUE TITLE
Suggestion: exclude RecSrcDt from form export to reduce noise

### ISSUE THREAD

**Issue by HughWarrington** [joyfullservice/msaccess-vcs-addin#516]
Here's an example file which I generated using this tool, a form with name `forms\MyForm.bas`:

```.bas
Version =19
VersionRequired =19
Begin Form
    AutoCenter = NotDefault
    PictureAlignment =2
    DatasheetGridlinesBehavior =3
    GridY =10
    Width =8277
    DatasheetFontHeight =10
    ItemSuffix =31
    Left =3645
    Top =21210
    Right =12360
    Bottom =24735
    DatasheetGridlinesColor =12632256
    RecSrcDt = Begin
        0x4ed191ac58dae540
    End
    RecordSource ="SELECT * FROM AnsRptProbs WHERE Subjid = 6"
'
'[...]
'
```

`RecSrcDt` appears to be undocumented, but speculation on the web points to it being some Access-internal property which Access churns over time. Could we exclude that from exports to reduce noise, or is it actually serving a purpose?

**Comment by HughWarrington** [comment]
Extra info: `RecSrcDt` seems to change when the `RecordSource` property changes. So maybe it's not just noise? I don't know how to test this... maybe import a form with no RecSrcDt set?

**Comment by bclothier** [comment]
It appears to function as a hash of the `Recordsource`. 

I would consider excluding it if it can be demonstrated that it can change even though the `Recordsource` did not change. If it always changes in lockstep to the `Recordsource`, then it shouldn't matter.

**Comment by HughWarrington** [comment]
I'm new round here and I'm not sure what the current policy is, but seems to me if RecSrcDt is an opaque string that is meaningless to a human, and isn't necessary for the add-in's import functionality, then it might as well be left out. But I'm not sure about that second part and haven't tested it.

**Comment by bclothier** [comment]
I get the reasoning for not want to include opaque stuff but generally it's better to keep the original source as intact as possible because we don't have full visibility into what Access does in the background with those opaque stuff so if it does not generate noises and has a 1:1 correspondence with the `Recordsource` then I'm inclined to leave it alone, even though it may generate an extra line of difference when comparing. 

Just in case, this may be helpful: [Why ami I seeing a large number of changed files after building my project from source](https://github.com/joyfullservice/msaccess-vcs-addin/wiki/FAQs#why-am-i-seeing-a-large-number-of-changed-files-after-building-my-project-from-source).

**Comment by HughWarrington** [comment]
OK, sounds good to me. Thanks for the feedback.
