### ISSUE TITLE
Centralize all TableDef .Connect properties in one file

### ISSUE THREAD

**Issue by mwolfe02** [joyfullservice/msaccess-vcs-addin#517]
I'm continuing to work on switching from my custom-built version control script to this add-in.  For the most part, it's been a breath of fresh air, but I'm hitting some areas of friction.  One of the biggest ones is the inclusion of the .Connect property in every table def file.

I understand why it's there for consistency, but it generates a _ton_ of noise when relinking tables.  When I make a simple switch--from dev to production or vice versa--I end up with dozens of changed files, almost all of them differing only by the .Connect property.  I dealt with this in my own script by centralizing all the .Connect properties in a single file.

Here's an excerpt from [my article](https://nolongerset.com/tracking-table-structure-changes/#the-_tablelist-table-file) on the topic:

> Once your schema is in place, it's relatively rare to have changes to the .table files that hold the field and index information for each table.  However, the TableDef.Connect property will often change en masse when switching data environments, such as from development to production.  
>
> If we included the .Connect property in each individual table file, there would be a huge number of changed files every time we switched environments.  A single change like that, especially one that happens relatively often, should not trigger a slew of changes to dozens--or even hundreds--of files.  All that noise will lead us to miss meaningful changes between revisions.
>
> To avoid this problem, I store all of the TableDef.Connect strings in a special text file named _TableList.table.  There's nothing special about this name, other than it is consistent across all of my repositories.  The consistency is important.  Feel free to change it to whatever you like, but DO NOT change it once you start using it.  

Check out the full article for sample code and other benefits of this approach (e.g., being able to search multiple front-end applications to see which apps link to which back-end tables).

One way to implement this to minimize disruption for existing users would be to make this an opt-in feature by adding a new option in the Export tab, such as:

- [ ] Centralize Connect Strings

**Comment by hecon5** [comment]
oooh, we had this issue too, and struggled with it for a good while before we decided on a fairly easy (for us) path: only build to dev, and never commit production tables connections to the repository. 

This has a few upsides, with few downsides.
1. Enforces that the stable/ dev / whatever branch changes are always the same and the only change is the test/production backend(s), and we can use merging to deploy. Since we always test on dev right before deploying, this helps too.
2. Reduces code noise when doing change reviewss.
3. Eliminates upstream/downstream merge conflicts when we merge a change back from production and our production never gets ahead of the test (This happens if you do a merge, then change the stable branch but don't commit it back upstream. it gets messy).
4. We don't build, then do testing, only to find out that row you just deleted to test the delete feature was on production because you got your worktree mixed up. This happened a few times before we only build to test backends.

We built a tool that automatically goes through all tables linked to a particular connection and relinks them from dev to production. We only have one backend server per db, but we did test this out and it will let you use two backend servers if you like, it just takes two steps (switch server 1 from dev to production, then switch server 2 from dev to production). Depending on geographic separation from your backend, this can be very fast for even 150 tables. If you're half a country away, this may take longer (takes me ~2.5 minutes to relink 140 tables at the moment when I'm ~2000 miles from our server).

This actually became a really nice safety mechanism as we have a pre-deploy step that checks the tables for test/production state and will alarm if you try to deploy a non-production db. 

This dramatically cut down on noise for us during code reviews, too. Though admittedly, when we do the final export after deploying (to capture the deployed version) we do have to make sure we don't accidentally commit the production connection files. With enforced merge requests, this is a really easy thing to validate before approving merge requests (for us). 

I do see the upside of a single file, though, and having fewer noise / repeated data would make for a cleaner sanitize, I will say after reading your article, I do think if this tool did put all connect strings in one file it would be best to put it into a JSON. JSON seems the most consistent method used in this tool, and avoids many pitfalls found when trying to import / export CSV or XML. JSON also (with `modJSONConverter`) imports directly to a dictionary, which is can then be dealt with during import / export and using keys makes it even faster to check for data.

If we did have a single file for the connections (shoot, even tables), you could organize it quite simply: 

- Connection 'n'
    - Connection String
    - Other attributes
    - Tables Using this connection
    - Queries Using this connection

Then, when you switch a connection from test/production, and it went correctly, the Only change you'll see is this: 

``` diff
 - Connection 'n'
--    - Connection String
++    - Connection String
    - Other attributes
    - Tables Using this connection
        - Table 1
        - Table 2 
        - Table n
    - Queries Using this connection
        - Q1
        - Q2
        - Qn
```

Then, if something did happen, and a table didn't correctly switch, you'd end up with this:

``` diff
 - Connection 'n'
--    - Connection String
++    - Connection String
    - Other attributes
    - Tables Using this connection
        - Table 1
--        - Table 2 
        - Table n
    - Queries Using this connection
        - Q1
        - Q2
        - Qn

++ - Connection 'n'
++    - Connection String
++    - Connection String
++    - Other attributes
++    - Tables Using this connection
++        - Table 2 
```

... Actually, despite me initially thinking this is a lot of work for not a lot of upside, I can see this may be helpful. Still a lot of work, but if you don't want to only commit connections that are built to test, this could be helpful.

Taking this even a step further, you could even 'hang' the tables/etc. off this too, so only one file is needed for all tables/ queries.
- Connection 'n'
    - Connection String
    - Other attributes
    - Tables Using this connection
        - T1 name
            - Table attributes
            - other info/details.
    - Queries Using this connection

**Comment by hecon5** [comment]
So, I was thinking about this some more, and the more I think about it, having all the connections in one file (or each connection in their own file with pointers) is a fair bit more complex, breaks the modularity of being able to drop one file from one project into another and build the database which is present now, and could pretty dramatically increase the addin code maintenance/complexity and also increasing the dev-side workload. This could be done, but it would need to be carefully managed to ensure the user workflows don't encounter unintended side effects.

# TL/DR: 
Suggest keeping as-is. I suggest only committing connections to your dev backend (or some dummy string if needed), use out of add-in tools to manage the connection targets OR integrate switching tools with the addin but make them totally optional so devs can continue their existing workflow as needed. Having pointers to connection strings could be useful when you don't want to commit any connection strings to your code base, but the more I think of it: you **WANT** the code noise when you switch your connection strings. Hear me out.

# Longer Diatribe:
Diffs **SHOULD** show code noise when something changes; that's the point of using code control tools. Having something change and then not knowing about it can lead to inconsistent builds and / or catastrophic outcomes if you build to production and expect to be on test...it could lead to a test script blowing up production (ask me how I know...).

## Low - change Mechanism:
ALWAYS build into test; NEVER build directly to production.
We maintain a table (deleted before deployment) on our front end. The table and data is exported and stored with the code base via the add-in and a form that is only accessible by devs (we deploy as an ACCDE so this isn't too troublesome) which will allow devs to switch the backend connections. Before deployment the last thing that's done is the table is blown away (so users can't inadvertently switch backends and wreak havoc or decompile and find our test servers). This keeps the code maintenance down to a bare minimum (for us).

- Table holding local connection strings
    - ![image](https://github.com/joyfullservice/msaccess-vcs-addin/assets/54177882/2ef139f2-eb48-41f2-a26d-8a70eda7a20f)

    - ![image](https://github.com/joyfullservice/msaccess-vcs-addin/assets/54177882/7833bfe4-c2e0-4e27-bb94-88cbedc34d01)

    - ![image](https://github.com/joyfullservice/msaccess-vcs-addin/assets/54177882/12e27103-b34f-4fc3-8d38-603da4093b1c)

- Tool to retarget linked tables and queries: 
    - ![image](https://github.com/joyfullservice/msaccess-vcs-addin/assets/54177882/4ccfccd2-6619-4778-92e4-273dfd47382a)
    - ![image](https://github.com/joyfullservice/msaccess-vcs-addin/assets/54177882/5d6b770d-4b9c-4455-86d8-32dfdc66dc75)



## Workflow example using this mechanism: 
1. Devs create a linked table/query for use. 
2. Devs export the db, they get one file that's the whole shebang for that table. 
3. The only change we need to commit is that single file; there's nothing else that changed code-wise.
4. If/when devs need/want to use this in a separate db/module, all they need to do is drag that file over to the other code folders and build.
    A. NOTE: If this table uses a new connection string (something other than your already setup servers/databases), you will need to add this new connection string to the table mentioned above. We manage only a few backends, so this is not an issue usually. 
5. Boom, table/query is built.
6. Switching backends, devs will open the backend tool, select the requisite backend, and then press go. 
7. Backends get switched, devs don't need to track per-table / query settings, and changing the connection string becomes very easy. 

So, with that, I think if hiding the strings is desired, the way to do it is to have each connection be its own file, use a consistent file naming scheme, then in the table/query file use some linking variable to point to the connection. 

This does have a drawback, though; in that to make it 'easy', the file name would be based on some combination of the server/path, and the database name. Switching from test to production would change this name, and therefore change the file name which then creates noise in the original files (where you wanted to avoid this in the first place).

To avoid that, users would have to setup a table / list of connections manually, name them something, and manage that. As part of the deploy, they could set a flag that connects to the correct backend (production/test/dev/etc.).

This isn't insurmountable, but adds a fair bit of complexity, code management requirements to the add-in, adds a non-zero amount of work for devs (that cannot be 'easily' automated as changing strings would by definition change the auto-naming).

All this to say: despite my prior post's conclusion, @mwolfe02, I think the best way for now with a decent maintenance/utility ratio: only build from dev/test, and use non-addin tools to switch backends.

I'd be happy to share my tools we've built to switch from dev to test to production, and perhaps they'd fit in; but the more I think about it, the more complex it is to manage the different connections without confusing them and ensuring a consistent modular approach.

**Comment by mwolfe02** [comment]
> Having pointers to connection strings could be useful when you don't want to commit any connection strings to your code base, but the more I think of it: you WANT the code noise when you switch your connection strings. Hear me out.

To be clear, I would commit the centralized file with the connection strings.  But it would be just one file, rather than dozens.  

That said, after reading the responses from @hecon5 and @joyfullservice, I'm convinced **the proper way forward is to leave the add-in unchanged**.  Whether I change my workflow to only commit from dev OR use the AfterExport/BeforeBuild events to make the add-in work with my existing workflow is something I'll have to give some further consideration.

Thanks to both of you for your well-thought-out answers.
