### ISSUE TITLE
Include event procedure name in .bas output

### ISSUE THREAD

**Issue by HughWarrington** [joyfullservice/msaccess-vcs-addin#519]
I'm using VCS 4.0.34.

This is a snippet from a .bas file as output by the tool currently (some irrelevant properties removed for brevity):

```.vba
Begin TextBox
    Name ="Qid_or_Qnumstr"
    OnKeyDown ="[Event Procedure]"
    Begin
        Begin Label
            ForeColor =16711680
            Name ="QidOrNumLabel"
            Caption ="Question ID or Number"
        End
    End
End
```

Would it be possible for the actual name of the event handler to appear instead of `[Event Procedure]`? This would make it much easier to work out when the event has been bound to a different handler, and when a particular procedure has become disused etc.

**Comment by HughWarrington** [comment]
Thank you for the thorough response.

Based on what you've said, I think it would be an improvement to always have the event procedure name listed explicitly, even if it has the default name.

It enables my use case, which is to grep the codebase and git log for occurrences of a particular sub name: I would be able to instantly see where the sub is defined, and also where it is used. At the moment I have to know about the default naming rule, and do a small translation in my head between what the control would be called or vice versa.

As a newcomer to this tool (and a relative newcomer to Access overall), I wasted a couple of hours today on the incorrect assumption that if a sub name didn't appear anywhere other than its definition, it was unused and could be deleted. Of course I blame Microsoft for that poor decision, not the authors of this wonderful addin.

I think in a small way this would contribute to the goal "Make human-readable data that isn't otherwise capturable".

As to whether this feature is worth the effort or is possible at all, I leave that to you. Feel free to close this ticket if it's a no go :)

**Comment by hecon5** [comment]
I think it would require a non-insignificant amount of legwork to get this done; and we'd need to track both whether the "name" is the standard or if it's something else AND then re-build this on import (as-is, the line just gets imported without modification). This would require building out a parser to interpret, and match the in-module "standard" named routines (so they are tracked), and non-standard, which would likely require a decoder ring file on import, etc. 

I think in this case, the utility is outweighed by the complexity of implementation. @joyfullservice: since I can't close things here, I'll leave the final determination to you ;). Or you can close it @HughWarrington, too.

That said: since you've inherited a code base, as someone who also inherited a sprawling code base, one mantra which serves me well (one that I keep learning over and over) is this: 
- First, **Do No Harm**. Don't delete stuff that's working just to clear out the cobwebs (more on that later).
- Second, **if it works now, don't touch it**. Seriously Having code bloat is better than broken code you yell into the void to fix.
- Third, **if it's broken, then make sure you make frequent code commits**...you will end up rolling something back, and having more granularity to unwind makes life easier. 
- When it's time to refactor / remove that bit: make dang sure it's not somehow connected to some seemingly completely unrelated function or form...past devs of my project were notorious for this. 

This has meant we still have a fair bit of code that's just ... there. Even forms I nearly fully refactor I end up leaving some functions alone simply because they still work and I don't desire to go through full validation when the mission is something completely different. Shoot, we still have some forms that don't get called up anymore because they contain some code that's called by some oddball routine which we don't want to mess with (yet).

My time is valuable as I want it to be, yours should be, too.

**Comment by HughWarrington** [comment]
Fair enough. It does sound complicated to implement.

Thanks a lot for the tips on working with the inherited code base. I'm not even trying to refactor anything yet. However there are about 50 different versions of this product out there in the wild, and the question is, what are the differences between each version? There was no version control or documentation, I just have the 50 .mdb files, and they aren't necessarily in chronological order (i.e. there may have been some 'branching' going on in the development). You can imagine what a nightmare this task is.

**Comment by joyfullservice** [comment]
As to the original question, I think my leaning would be to leave the export file just as it is in this regard. While adding in the function name could be useful in some scenarios, it does deviate from the standard format to something custom that could actually require even more effort to troubleshoot in the future. (Some of Mike Wolfe's [articles](https://nolongerset.com/dont-write-clever-code/) come to mind here...)

I have been involved in a multi-year rewrite of a core business software application, upgrading it from Access 2000 to 2010 and doing a lot of cleanup in the process. In addition to the tips shared by @hecon5, here are a few things I have found helpful in the process:

- Implement version control as early as possible in the process.
- Phase 1 was to get option explicit turned on for the project, making sure that every variable was properly declared. This greatly helps with debugging later on.
- Rather than deleting code, I would use the toolbar option to comment out large sections that didn't seem to be needed/used anymore. If the project still compiled, I could be about 90% sure the code wasn't used. [DocFetcher](https://docfetcher.sourceforge.io/en/index.html) provides near instant search results across all of the source files, so that is another very helpful tool in identifying where functions were used.
- After running the application for several months with the code commented out, I would go back in and remove those commented blocks. I could still find them in VCS if needed down the road, but the less you have to scroll through, the easier it is to maintain going forward.
- If you are dealing with a lot of different versions of the .mdb files, it can be helpful to use this add-in to export each one into source files, and then use WinMerge or other diff program to quickly identify the differences between them.

All the best on your project!
