### ISSUE TITLE
Full Export Does not Trigger Full Export On Schema (MSSQL)

### ISSUE THREAD

**Issue by hecon5** [joyfullservice/msaccess-vcs-addin#548]
When doing a full export, the SQL exporting tool still only does a compare regardless of export type (fast, full, etc.).

**Comment by joyfullservice** [comment]
This is by design. A full SQL export can take a long time, especially if there are hundreds or thousands of entities on the SQL server. If you want a full refresh, you can delete the subfolder in the source files and it will regenerate them on the next export. There are times when you need to do a full export of the Access database, such as after a build from source, but I don't see any benefit to adding the time to regenerate all the SQL objects as well.

Is there a case where you feel like it would be important to regenerate all the files? The index is already managing changes, so you shouldn't have cases where SQL object changes were not picked up during an export.

**Comment by hecon5** [comment]
I think realistically, no. In practice, seeing "perform full export" checked and it not exporting the SQL as well can be confusing, so it's not expected behavior. 

I think we could update the Wiki on this to highlight that behavior or add an option to the Database to perform a full export when the full export is checked so it behaves  as expected.

**Comment by hecon5** [comment]
Added documentation on how sql export works in ada83e89a592f2183c3ad4f627699a09fcd0541e and PR #550
